version: '3.8'

services:
  cognito-local:
    image: jagregory/cognito-local:latest
    ports:
      - "9229:9229"
    volumes:
      - ./cognito-local/.cognito:/app/.cognito
    environment:
      - NODE_ENV=development
